### ISSUE TITLE
TODO: review code flagged as 'potential bug' by quantifiedcode

### ISSUE THREAD

**Issue by hanleybrand** [hanleybrand/rooibos#8]
See https://www.quantifiedcode.com/app/project/0094577cbd774ac9a1f3d0f220bf6a49?severity=2&groups=code_patterns%3A1Wit6MHp&tab=badges

**Comment by hanleybrand** [comment]
- [ ] Avoid accessing protected class members from outsideLearn  17 files affected.
- [ ] Avoid mutable default argumentsLearn  5 files affected.
- [ ] Avoid using wildcard (*) importsLearn  25 files affected. 
- [ ] Use of `eval()`Learn  3 files affected.
- [ ] Unreachable codeLearn 1 file affected.
- [ ] `dict.has_key()` deprecated  25 files affected.
- [ ]  Duplicate key in dictionary
